apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.network/myapp: "true"
      io.kompose.service: back
  template:
    metadata:
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: back
    spec:
      containers:
      - image: thelesik/quotes-back:v2
        name: api
        ports:
        - containerPort: 3000
        env:
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SQLALCHEMY_DATABASE_URI
                optional: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: back
  name: api
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.network/myapp: "true"
    io.kompose.service: back
