apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  SQLALCHEMY_DATABASE_URI: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdEBkYXRhOjMzMDYvbXlkYXRhYmFzZQ==
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_ALLOW_EMPTY_PASSWORD: InllcyI=
  MYSQL_DB_HOST: ZGF0YQ==
  MYSQL_USER: cm9vdA==
  MYSQL_USER_PASSWORD: cm9vdA==
